### ISSUE TITLE
Erro 500 no UPDATE para cliente com id que não existe

### ISSUE THREAD

**Issue by oliveiralex** [nilson-roman/dsprojetocrud#1]
Boa noite Nilson,

Seu trabalho já está aceito, parabéns! Mas para ficar 100%, favor incluir o tratamento de exceções. Está retornando erro 500 ao atualizar (UPDATE) um cliente com id inexistente.

**Comment by nilson-roman** [comment]
Opa boa noite Alexandre, muito obrigado pelo feedback. Realmente esse erro acabou passando, já atualizei o commit com o tratamento correto para o update.

**Comment by oliveiralex** [comment]
Maravilha Nilson! Um abraço
